name: Deploy Package

on:
  push:
    branches: [release]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Node Version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Deps
        run: yarn install

      - name: Build Release Package
        run: yarn build-package

      - name: Publish To NPM
        run: npm publish ./package --provenance --access public
